// src/src/routes/login/+page.svelte
<script>
    import * as Card from "$lib/components/ui/card/";
    import { Button } from "$lib/components/ui/button/";
    import { Input } from "$lib/components/ui/input/";

    import { goto } from "$app/navigation";

    import { pb, currentUser } from "$lib/pb";

    let email = "";
    let password = "";

    let response = "";

    async function login() {
        const pb_response = await pb
            .collection("users")
            .authWithPassword(email, password);

        goto("/dashboard");

        response = JSON.stringify(pb_response, null, 2);
    }
</script>

{#if $currentUser}
    <p>Already logged in as {$currentUser.email}</p>
    <button
        on:click={() => {
            pb.authStore.clear();
        }}>Logout</button
    >
{:else}
    <Card.Root class="m-10 p-10">
        <Card.Header>
            <Card.Title>Login to your account</Card.Title>
            <Card.Description>Create your deck in seconds.</Card.Description>
        </Card.Header>

        <Card.Content>
            <Input
                class="mt-2"
                id="email"
                placeholder="example@example.com"
                bind:value={email}
            />
            <Input
                class="mt-2"
                type="password"
                id="password"
                placeholder="password"
                bind:value={password}
            />

            <div class="p-2">{response}</div>
        </Card.Content>

        <Card.Footer class="flex justify-between">
            <Button on:click={login}>Login</Button>
            <p>
                Don't have an account??
                <a href="/register"><strong>register</strong></a>
            </p>
        </Card.Footer>
    </Card.Root>
{/if}

// src/src/routes/login.tsx
import {
    Card,
    CardContent,
    CardDescription,
    CardFooter,
    CardHeader,
    CardTitle,
} from "@/components/ui/card";

import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";

import { usePocket } from "@/contexts/pb";

import { useCallback, useRef } from "react";
import { Link, useNavigate } from "react-router-dom";

export const Login = () => {
    const emailRef = useRef<HTMLInputElement>(null);
    const passwordRef = useRef<HTMLInputElement>(null);
    const passwordConfirmRef = useRef<HTMLInputElement>(null);

    const navigate = useNavigate();


    const { user, login, logout } = usePocket();

    if (user) {
        return <div>
            Already logged in as: {JSON.stringify(user)}
            <Button onClick={logout}>Logout</Button>
        </div>;
    }

    const handleSubmit = async (event: any) => {

        if (!emailRef.current?.value || !passwordRef.current?.value) {
            return;
        }

        await login(emailRef.current.value, passwordRef.current.value,);

        navigate("/dashboard");

    };

    return (
        <div className="max-w-2xl mx-auto mt-10">
            <Card>
                <CardHeader>
                    <CardTitle>Login</CardTitle>
                    <CardDescription>
                        Create your deck in seconds.
                    </CardDescription>
                </CardHeader>

                <CardContent>
                    <Input
                        ref={emailRef}
                        type="email"
                        placeholder="example@example.com"
                        className="mb-2"
                    />
                    <Input
                        ref={passwordRef}
                        type="password"
                        placeholder="password"
                        className="mb-2"
                    />
                </CardContent>
                <CardFooter className="flex justify-between">
                    <Button onClick={handleSubmit}>Login</Button>
                    <Link to="/register">Don't have an account? Register</Link>
                </CardFooter>
            </Card>
        </div>
    );
};

export default Login;
